package com.lxy.exchange.dao;

import com.lxy.exchange.entity.Offer;
import com.lxy.exchange.entity.OfferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    long countByExample(OfferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    int deleteByExample(OfferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    int deleteByPrimaryKey(String oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    int insert(Offer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    int insertSelective(Offer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    List<Offer> selectByExample(OfferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    Offer selectByPrimaryKey(String oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Offer record, @Param("example") OfferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    int updateByExample(@Param("record") Offer record, @Param("example") OfferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    int updateByPrimaryKeySelective(Offer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    int updateByPrimaryKey(Offer record);
}