package com.lxy.exchange.entity;

import java.io.Serializable;

public class Item implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_list.id
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_list.author_id
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_list.title
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_list.subtitle
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_list.publish_time
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_list
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_list.id
     *
     * @return the value of item_list.id
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_list.id
     *
     * @param id the value for item_list.id
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_list.author_id
     *
     * @return the value of item_list.author_id
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_list.author_id
     *
     * @param authorId the value for item_list.author_id
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_list.title
     *
     * @return the value of item_list.title
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_list.title
     *
     * @param title the value for item_list.title
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_list.subtitle
     *
     * @return the value of item_list.subtitle
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_list.subtitle
     *
     * @param subtitle the value for item_list.subtitle
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_list.publish_time
     *
     * @return the value of item_list.publish_time
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_list.publish_time
     *
     * @param publishTime the value for item_list.publish_time
     *
     * @mbg.generated Wed Feb 19 21:27:16 CST 2020
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime;
    }
}