package com.lxy.exchange.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OfferExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public OfferExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOIdIsNull() {
            addCriterion("o_id is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("o_id is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(String value) {
            addCriterion("o_id =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(String value) {
            addCriterion("o_id <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(String value) {
            addCriterion("o_id >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(String value) {
            addCriterion("o_id >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(String value) {
            addCriterion("o_id <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(String value) {
            addCriterion("o_id <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLike(String value) {
            addCriterion("o_id like", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotLike(String value) {
            addCriterion("o_id not like", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<String> values) {
            addCriterion("o_id in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<String> values) {
            addCriterion("o_id not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(String value1, String value2) {
            addCriterion("o_id between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(String value1, String value2) {
            addCriterion("o_id not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOUseridIsNull() {
            addCriterion("o_userid is null");
            return (Criteria) this;
        }

        public Criteria andOUseridIsNotNull() {
            addCriterion("o_userid is not null");
            return (Criteria) this;
        }

        public Criteria andOUseridEqualTo(String value) {
            addCriterion("o_userid =", value, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridNotEqualTo(String value) {
            addCriterion("o_userid <>", value, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridGreaterThan(String value) {
            addCriterion("o_userid >", value, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridGreaterThanOrEqualTo(String value) {
            addCriterion("o_userid >=", value, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridLessThan(String value) {
            addCriterion("o_userid <", value, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridLessThanOrEqualTo(String value) {
            addCriterion("o_userid <=", value, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridLike(String value) {
            addCriterion("o_userid like", value, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridNotLike(String value) {
            addCriterion("o_userid not like", value, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridIn(List<String> values) {
            addCriterion("o_userid in", values, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridNotIn(List<String> values) {
            addCriterion("o_userid not in", values, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridBetween(String value1, String value2) {
            addCriterion("o_userid between", value1, value2, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUseridNotBetween(String value1, String value2) {
            addCriterion("o_userid not between", value1, value2, "oUserid");
            return (Criteria) this;
        }

        public Criteria andOUsageIsNull() {
            addCriterion("o_usage is null");
            return (Criteria) this;
        }

        public Criteria andOUsageIsNotNull() {
            addCriterion("o_usage is not null");
            return (Criteria) this;
        }

        public Criteria andOUsageEqualTo(Integer value) {
            addCriterion("o_usage =", value, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageNotEqualTo(Integer value) {
            addCriterion("o_usage <>", value, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageGreaterThan(Integer value) {
            addCriterion("o_usage >", value, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_usage >=", value, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageLessThan(Integer value) {
            addCriterion("o_usage <", value, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageLessThanOrEqualTo(Integer value) {
            addCriterion("o_usage <=", value, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageIn(List<Integer> values) {
            addCriterion("o_usage in", values, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageNotIn(List<Integer> values) {
            addCriterion("o_usage not in", values, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageBetween(Integer value1, Integer value2) {
            addCriterion("o_usage between", value1, value2, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOUsageNotBetween(Integer value1, Integer value2) {
            addCriterion("o_usage not between", value1, value2, "oUsage");
            return (Criteria) this;
        }

        public Criteria andOTitleIsNull() {
            addCriterion("o_title is null");
            return (Criteria) this;
        }

        public Criteria andOTitleIsNotNull() {
            addCriterion("o_title is not null");
            return (Criteria) this;
        }

        public Criteria andOTitleEqualTo(String value) {
            addCriterion("o_title =", value, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleNotEqualTo(String value) {
            addCriterion("o_title <>", value, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleGreaterThan(String value) {
            addCriterion("o_title >", value, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleGreaterThanOrEqualTo(String value) {
            addCriterion("o_title >=", value, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleLessThan(String value) {
            addCriterion("o_title <", value, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleLessThanOrEqualTo(String value) {
            addCriterion("o_title <=", value, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleLike(String value) {
            addCriterion("o_title like", value, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleNotLike(String value) {
            addCriterion("o_title not like", value, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleIn(List<String> values) {
            addCriterion("o_title in", values, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleNotIn(List<String> values) {
            addCriterion("o_title not in", values, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleBetween(String value1, String value2) {
            addCriterion("o_title between", value1, value2, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTitleNotBetween(String value1, String value2) {
            addCriterion("o_title not between", value1, value2, "oTitle");
            return (Criteria) this;
        }

        public Criteria andOTypeIsNull() {
            addCriterion("o_type is null");
            return (Criteria) this;
        }

        public Criteria andOTypeIsNotNull() {
            addCriterion("o_type is not null");
            return (Criteria) this;
        }

        public Criteria andOTypeEqualTo(Integer value) {
            addCriterion("o_type =", value, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeNotEqualTo(Integer value) {
            addCriterion("o_type <>", value, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeGreaterThan(Integer value) {
            addCriterion("o_type >", value, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_type >=", value, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeLessThan(Integer value) {
            addCriterion("o_type <", value, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeLessThanOrEqualTo(Integer value) {
            addCriterion("o_type <=", value, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeIn(List<Integer> values) {
            addCriterion("o_type in", values, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeNotIn(List<Integer> values) {
            addCriterion("o_type not in", values, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeBetween(Integer value1, Integer value2) {
            addCriterion("o_type between", value1, value2, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("o_type not between", value1, value2, "oType");
            return (Criteria) this;
        }

        public Criteria andOTypetextIsNull() {
            addCriterion("o_typetext is null");
            return (Criteria) this;
        }

        public Criteria andOTypetextIsNotNull() {
            addCriterion("o_typetext is not null");
            return (Criteria) this;
        }

        public Criteria andOTypetextEqualTo(String value) {
            addCriterion("o_typetext =", value, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextNotEqualTo(String value) {
            addCriterion("o_typetext <>", value, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextGreaterThan(String value) {
            addCriterion("o_typetext >", value, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextGreaterThanOrEqualTo(String value) {
            addCriterion("o_typetext >=", value, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextLessThan(String value) {
            addCriterion("o_typetext <", value, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextLessThanOrEqualTo(String value) {
            addCriterion("o_typetext <=", value, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextLike(String value) {
            addCriterion("o_typetext like", value, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextNotLike(String value) {
            addCriterion("o_typetext not like", value, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextIn(List<String> values) {
            addCriterion("o_typetext in", values, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextNotIn(List<String> values) {
            addCriterion("o_typetext not in", values, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextBetween(String value1, String value2) {
            addCriterion("o_typetext between", value1, value2, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOTypetextNotBetween(String value1, String value2) {
            addCriterion("o_typetext not between", value1, value2, "oTypetext");
            return (Criteria) this;
        }

        public Criteria andOMinpriceIsNull() {
            addCriterion("o_minprice is null");
            return (Criteria) this;
        }

        public Criteria andOMinpriceIsNotNull() {
            addCriterion("o_minprice is not null");
            return (Criteria) this;
        }

        public Criteria andOMinpriceEqualTo(BigDecimal value) {
            addCriterion("o_minprice =", value, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceNotEqualTo(BigDecimal value) {
            addCriterion("o_minprice <>", value, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceGreaterThan(BigDecimal value) {
            addCriterion("o_minprice >", value, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("o_minprice >=", value, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceLessThan(BigDecimal value) {
            addCriterion("o_minprice <", value, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("o_minprice <=", value, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceIn(List<BigDecimal> values) {
            addCriterion("o_minprice in", values, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceNotIn(List<BigDecimal> values) {
            addCriterion("o_minprice not in", values, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_minprice between", value1, value2, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMinpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_minprice not between", value1, value2, "oMinprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceIsNull() {
            addCriterion("o_maxprice is null");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceIsNotNull() {
            addCriterion("o_maxprice is not null");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceEqualTo(BigDecimal value) {
            addCriterion("o_maxprice =", value, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceNotEqualTo(BigDecimal value) {
            addCriterion("o_maxprice <>", value, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceGreaterThan(BigDecimal value) {
            addCriterion("o_maxprice >", value, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("o_maxprice >=", value, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceLessThan(BigDecimal value) {
            addCriterion("o_maxprice <", value, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("o_maxprice <=", value, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceIn(List<BigDecimal> values) {
            addCriterion("o_maxprice in", values, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceNotIn(List<BigDecimal> values) {
            addCriterion("o_maxprice not in", values, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_maxprice between", value1, value2, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andOMaxpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_maxprice not between", value1, value2, "oMaxprice");
            return (Criteria) this;
        }

        public Criteria andODeadlineIsNull() {
            addCriterion("o_deadline is null");
            return (Criteria) this;
        }

        public Criteria andODeadlineIsNotNull() {
            addCriterion("o_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andODeadlineEqualTo(String value) {
            addCriterion("o_deadline =", value, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineNotEqualTo(String value) {
            addCriterion("o_deadline <>", value, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineGreaterThan(String value) {
            addCriterion("o_deadline >", value, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineGreaterThanOrEqualTo(String value) {
            addCriterion("o_deadline >=", value, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineLessThan(String value) {
            addCriterion("o_deadline <", value, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineLessThanOrEqualTo(String value) {
            addCriterion("o_deadline <=", value, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineLike(String value) {
            addCriterion("o_deadline like", value, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineNotLike(String value) {
            addCriterion("o_deadline not like", value, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineIn(List<String> values) {
            addCriterion("o_deadline in", values, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineNotIn(List<String> values) {
            addCriterion("o_deadline not in", values, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineBetween(String value1, String value2) {
            addCriterion("o_deadline between", value1, value2, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andODeadlineNotBetween(String value1, String value2) {
            addCriterion("o_deadline not between", value1, value2, "oDeadline");
            return (Criteria) this;
        }

        public Criteria andOColorpattenIsNull() {
            addCriterion("o_colorpatten is null");
            return (Criteria) this;
        }

        public Criteria andOColorpattenIsNotNull() {
            addCriterion("o_colorpatten is not null");
            return (Criteria) this;
        }

        public Criteria andOColorpattenEqualTo(String value) {
            addCriterion("o_colorpatten =", value, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenNotEqualTo(String value) {
            addCriterion("o_colorpatten <>", value, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenGreaterThan(String value) {
            addCriterion("o_colorpatten >", value, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenGreaterThanOrEqualTo(String value) {
            addCriterion("o_colorpatten >=", value, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenLessThan(String value) {
            addCriterion("o_colorpatten <", value, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenLessThanOrEqualTo(String value) {
            addCriterion("o_colorpatten <=", value, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenLike(String value) {
            addCriterion("o_colorpatten like", value, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenNotLike(String value) {
            addCriterion("o_colorpatten not like", value, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenIn(List<String> values) {
            addCriterion("o_colorpatten in", values, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenNotIn(List<String> values) {
            addCriterion("o_colorpatten not in", values, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenBetween(String value1, String value2) {
            addCriterion("o_colorpatten between", value1, value2, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattenNotBetween(String value1, String value2) {
            addCriterion("o_colorpatten not between", value1, value2, "oColorpatten");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextIsNull() {
            addCriterion("o_colorpattentext is null");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextIsNotNull() {
            addCriterion("o_colorpattentext is not null");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextEqualTo(String value) {
            addCriterion("o_colorpattentext =", value, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextNotEqualTo(String value) {
            addCriterion("o_colorpattentext <>", value, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextGreaterThan(String value) {
            addCriterion("o_colorpattentext >", value, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextGreaterThanOrEqualTo(String value) {
            addCriterion("o_colorpattentext >=", value, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextLessThan(String value) {
            addCriterion("o_colorpattentext <", value, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextLessThanOrEqualTo(String value) {
            addCriterion("o_colorpattentext <=", value, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextLike(String value) {
            addCriterion("o_colorpattentext like", value, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextNotLike(String value) {
            addCriterion("o_colorpattentext not like", value, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextIn(List<String> values) {
            addCriterion("o_colorpattentext in", values, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextNotIn(List<String> values) {
            addCriterion("o_colorpattentext not in", values, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextBetween(String value1, String value2) {
            addCriterion("o_colorpattentext between", value1, value2, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOColorpattentextNotBetween(String value1, String value2) {
            addCriterion("o_colorpattentext not between", value1, value2, "oColorpattentext");
            return (Criteria) this;
        }

        public Criteria andOWidthIsNull() {
            addCriterion("o_width is null");
            return (Criteria) this;
        }

        public Criteria andOWidthIsNotNull() {
            addCriterion("o_width is not null");
            return (Criteria) this;
        }

        public Criteria andOWidthEqualTo(BigDecimal value) {
            addCriterion("o_width =", value, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthNotEqualTo(BigDecimal value) {
            addCriterion("o_width <>", value, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthGreaterThan(BigDecimal value) {
            addCriterion("o_width >", value, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("o_width >=", value, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthLessThan(BigDecimal value) {
            addCriterion("o_width <", value, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("o_width <=", value, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthIn(List<BigDecimal> values) {
            addCriterion("o_width in", values, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthNotIn(List<BigDecimal> values) {
            addCriterion("o_width not in", values, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_width between", value1, value2, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOWidthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_width not between", value1, value2, "oWidth");
            return (Criteria) this;
        }

        public Criteria andOHeightIsNull() {
            addCriterion("o_height is null");
            return (Criteria) this;
        }

        public Criteria andOHeightIsNotNull() {
            addCriterion("o_height is not null");
            return (Criteria) this;
        }

        public Criteria andOHeightEqualTo(BigDecimal value) {
            addCriterion("o_height =", value, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightNotEqualTo(BigDecimal value) {
            addCriterion("o_height <>", value, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightGreaterThan(BigDecimal value) {
            addCriterion("o_height >", value, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("o_height >=", value, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightLessThan(BigDecimal value) {
            addCriterion("o_height <", value, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("o_height <=", value, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightIn(List<BigDecimal> values) {
            addCriterion("o_height in", values, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightNotIn(List<BigDecimal> values) {
            addCriterion("o_height not in", values, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_height between", value1, value2, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOHeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_height not between", value1, value2, "oHeight");
            return (Criteria) this;
        }

        public Criteria andOUnitIsNull() {
            addCriterion("o_unit is null");
            return (Criteria) this;
        }

        public Criteria andOUnitIsNotNull() {
            addCriterion("o_unit is not null");
            return (Criteria) this;
        }

        public Criteria andOUnitEqualTo(Integer value) {
            addCriterion("o_unit =", value, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitNotEqualTo(Integer value) {
            addCriterion("o_unit <>", value, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitGreaterThan(Integer value) {
            addCriterion("o_unit >", value, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_unit >=", value, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitLessThan(Integer value) {
            addCriterion("o_unit <", value, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitLessThanOrEqualTo(Integer value) {
            addCriterion("o_unit <=", value, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitIn(List<Integer> values) {
            addCriterion("o_unit in", values, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitNotIn(List<Integer> values) {
            addCriterion("o_unit not in", values, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitBetween(Integer value1, Integer value2) {
            addCriterion("o_unit between", value1, value2, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOUnitNotBetween(Integer value1, Integer value2) {
            addCriterion("o_unit not between", value1, value2, "oUnit");
            return (Criteria) this;
        }

        public Criteria andOFormatIsNull() {
            addCriterion("o_format is null");
            return (Criteria) this;
        }

        public Criteria andOFormatIsNotNull() {
            addCriterion("o_format is not null");
            return (Criteria) this;
        }

        public Criteria andOFormatEqualTo(String value) {
            addCriterion("o_format =", value, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatNotEqualTo(String value) {
            addCriterion("o_format <>", value, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatGreaterThan(String value) {
            addCriterion("o_format >", value, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatGreaterThanOrEqualTo(String value) {
            addCriterion("o_format >=", value, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatLessThan(String value) {
            addCriterion("o_format <", value, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatLessThanOrEqualTo(String value) {
            addCriterion("o_format <=", value, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatLike(String value) {
            addCriterion("o_format like", value, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatNotLike(String value) {
            addCriterion("o_format not like", value, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatIn(List<String> values) {
            addCriterion("o_format in", values, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatNotIn(List<String> values) {
            addCriterion("o_format not in", values, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatBetween(String value1, String value2) {
            addCriterion("o_format between", value1, value2, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormatNotBetween(String value1, String value2) {
            addCriterion("o_format not between", value1, value2, "oFormat");
            return (Criteria) this;
        }

        public Criteria andOFormattextIsNull() {
            addCriterion("o_formattext is null");
            return (Criteria) this;
        }

        public Criteria andOFormattextIsNotNull() {
            addCriterion("o_formattext is not null");
            return (Criteria) this;
        }

        public Criteria andOFormattextEqualTo(String value) {
            addCriterion("o_formattext =", value, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextNotEqualTo(String value) {
            addCriterion("o_formattext <>", value, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextGreaterThan(String value) {
            addCriterion("o_formattext >", value, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextGreaterThanOrEqualTo(String value) {
            addCriterion("o_formattext >=", value, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextLessThan(String value) {
            addCriterion("o_formattext <", value, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextLessThanOrEqualTo(String value) {
            addCriterion("o_formattext <=", value, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextLike(String value) {
            addCriterion("o_formattext like", value, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextNotLike(String value) {
            addCriterion("o_formattext not like", value, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextIn(List<String> values) {
            addCriterion("o_formattext in", values, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextNotIn(List<String> values) {
            addCriterion("o_formattext not in", values, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextBetween(String value1, String value2) {
            addCriterion("o_formattext between", value1, value2, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFormattextNotBetween(String value1, String value2) {
            addCriterion("o_formattext not between", value1, value2, "oFormattext");
            return (Criteria) this;
        }

        public Criteria andOFeedbackIsNull() {
            addCriterion("o_feedback is null");
            return (Criteria) this;
        }

        public Criteria andOFeedbackIsNotNull() {
            addCriterion("o_feedback is not null");
            return (Criteria) this;
        }

        public Criteria andOFeedbackEqualTo(Integer value) {
            addCriterion("o_feedback =", value, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackNotEqualTo(Integer value) {
            addCriterion("o_feedback <>", value, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackGreaterThan(Integer value) {
            addCriterion("o_feedback >", value, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_feedback >=", value, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackLessThan(Integer value) {
            addCriterion("o_feedback <", value, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackLessThanOrEqualTo(Integer value) {
            addCriterion("o_feedback <=", value, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackIn(List<Integer> values) {
            addCriterion("o_feedback in", values, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackNotIn(List<Integer> values) {
            addCriterion("o_feedback not in", values, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackBetween(Integer value1, Integer value2) {
            addCriterion("o_feedback between", value1, value2, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOFeedbackNotBetween(Integer value1, Integer value2) {
            addCriterion("o_feedback not between", value1, value2, "oFeedback");
            return (Criteria) this;
        }

        public Criteria andOTestdrwIsNull() {
            addCriterion("o_testdrw is null");
            return (Criteria) this;
        }

        public Criteria andOTestdrwIsNotNull() {
            addCriterion("o_testdrw is not null");
            return (Criteria) this;
        }

        public Criteria andOTestdrwEqualTo(Integer value) {
            addCriterion("o_testdrw =", value, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwNotEqualTo(Integer value) {
            addCriterion("o_testdrw <>", value, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwGreaterThan(Integer value) {
            addCriterion("o_testdrw >", value, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_testdrw >=", value, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwLessThan(Integer value) {
            addCriterion("o_testdrw <", value, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwLessThanOrEqualTo(Integer value) {
            addCriterion("o_testdrw <=", value, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwIn(List<Integer> values) {
            addCriterion("o_testdrw in", values, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwNotIn(List<Integer> values) {
            addCriterion("o_testdrw not in", values, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwBetween(Integer value1, Integer value2) {
            addCriterion("o_testdrw between", value1, value2, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOTestdrwNotBetween(Integer value1, Integer value2) {
            addCriterion("o_testdrw not between", value1, value2, "oTestdrw");
            return (Criteria) this;
        }

        public Criteria andOPublishstateIsNull() {
            addCriterion("o_publishstate is null");
            return (Criteria) this;
        }

        public Criteria andOPublishstateIsNotNull() {
            addCriterion("o_publishstate is not null");
            return (Criteria) this;
        }

        public Criteria andOPublishstateEqualTo(Integer value) {
            addCriterion("o_publishstate =", value, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateNotEqualTo(Integer value) {
            addCriterion("o_publishstate <>", value, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateGreaterThan(Integer value) {
            addCriterion("o_publishstate >", value, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_publishstate >=", value, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateLessThan(Integer value) {
            addCriterion("o_publishstate <", value, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateLessThanOrEqualTo(Integer value) {
            addCriterion("o_publishstate <=", value, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateIn(List<Integer> values) {
            addCriterion("o_publishstate in", values, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateNotIn(List<Integer> values) {
            addCriterion("o_publishstate not in", values, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateBetween(Integer value1, Integer value2) {
            addCriterion("o_publishstate between", value1, value2, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishstateNotBetween(Integer value1, Integer value2) {
            addCriterion("o_publishstate not between", value1, value2, "oPublishstate");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeIsNull() {
            addCriterion("o_publishtime is null");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeIsNotNull() {
            addCriterion("o_publishtime is not null");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeEqualTo(String value) {
            addCriterion("o_publishtime =", value, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeNotEqualTo(String value) {
            addCriterion("o_publishtime <>", value, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeGreaterThan(String value) {
            addCriterion("o_publishtime >", value, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeGreaterThanOrEqualTo(String value) {
            addCriterion("o_publishtime >=", value, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeLessThan(String value) {
            addCriterion("o_publishtime <", value, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeLessThanOrEqualTo(String value) {
            addCriterion("o_publishtime <=", value, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeLike(String value) {
            addCriterion("o_publishtime like", value, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeNotLike(String value) {
            addCriterion("o_publishtime not like", value, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeIn(List<String> values) {
            addCriterion("o_publishtime in", values, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeNotIn(List<String> values) {
            addCriterion("o_publishtime not in", values, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeBetween(String value1, String value2) {
            addCriterion("o_publishtime between", value1, value2, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOPublishtimeNotBetween(String value1, String value2) {
            addCriterion("o_publishtime not between", value1, value2, "oPublishtime");
            return (Criteria) this;
        }

        public Criteria andOEndstateIsNull() {
            addCriterion("o_endstate is null");
            return (Criteria) this;
        }

        public Criteria andOEndstateIsNotNull() {
            addCriterion("o_endstate is not null");
            return (Criteria) this;
        }

        public Criteria andOEndstateEqualTo(Integer value) {
            addCriterion("o_endstate =", value, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateNotEqualTo(Integer value) {
            addCriterion("o_endstate <>", value, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateGreaterThan(Integer value) {
            addCriterion("o_endstate >", value, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_endstate >=", value, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateLessThan(Integer value) {
            addCriterion("o_endstate <", value, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateLessThanOrEqualTo(Integer value) {
            addCriterion("o_endstate <=", value, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateIn(List<Integer> values) {
            addCriterion("o_endstate in", values, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateNotIn(List<Integer> values) {
            addCriterion("o_endstate not in", values, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateBetween(Integer value1, Integer value2) {
            addCriterion("o_endstate between", value1, value2, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOEndstateNotBetween(Integer value1, Integer value2) {
            addCriterion("o_endstate not between", value1, value2, "oEndstate");
            return (Criteria) this;
        }

        public Criteria andOApplynumIsNull() {
            addCriterion("o_applynum is null");
            return (Criteria) this;
        }

        public Criteria andOApplynumIsNotNull() {
            addCriterion("o_applynum is not null");
            return (Criteria) this;
        }

        public Criteria andOApplynumEqualTo(Integer value) {
            addCriterion("o_applynum =", value, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumNotEqualTo(Integer value) {
            addCriterion("o_applynum <>", value, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumGreaterThan(Integer value) {
            addCriterion("o_applynum >", value, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_applynum >=", value, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumLessThan(Integer value) {
            addCriterion("o_applynum <", value, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumLessThanOrEqualTo(Integer value) {
            addCriterion("o_applynum <=", value, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumIn(List<Integer> values) {
            addCriterion("o_applynum in", values, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumNotIn(List<Integer> values) {
            addCriterion("o_applynum not in", values, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumBetween(Integer value1, Integer value2) {
            addCriterion("o_applynum between", value1, value2, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andOApplynumNotBetween(Integer value1, Integer value2) {
            addCriterion("o_applynum not between", value1, value2, "oApplynum");
            return (Criteria) this;
        }

        public Criteria andODescriptionIsNull() {
            addCriterion("o_description is null");
            return (Criteria) this;
        }

        public Criteria andODescriptionIsNotNull() {
            addCriterion("o_description is not null");
            return (Criteria) this;
        }

        public Criteria andODescriptionEqualTo(String value) {
            addCriterion("o_description =", value, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionNotEqualTo(String value) {
            addCriterion("o_description <>", value, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionGreaterThan(String value) {
            addCriterion("o_description >", value, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("o_description >=", value, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionLessThan(String value) {
            addCriterion("o_description <", value, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionLessThanOrEqualTo(String value) {
            addCriterion("o_description <=", value, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionLike(String value) {
            addCriterion("o_description like", value, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionNotLike(String value) {
            addCriterion("o_description not like", value, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionIn(List<String> values) {
            addCriterion("o_description in", values, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionNotIn(List<String> values) {
            addCriterion("o_description not in", values, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionBetween(String value1, String value2) {
            addCriterion("o_description between", value1, value2, "oDescription");
            return (Criteria) this;
        }

        public Criteria andODescriptionNotBetween(String value1, String value2) {
            addCriterion("o_description not between", value1, value2, "oDescription");
            return (Criteria) this;
        }

        public Criteria andOImgIsNull() {
            addCriterion("o_img is null");
            return (Criteria) this;
        }

        public Criteria andOImgIsNotNull() {
            addCriterion("o_img is not null");
            return (Criteria) this;
        }

        public Criteria andOImgEqualTo(String value) {
            addCriterion("o_img =", value, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgNotEqualTo(String value) {
            addCriterion("o_img <>", value, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgGreaterThan(String value) {
            addCriterion("o_img >", value, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgGreaterThanOrEqualTo(String value) {
            addCriterion("o_img >=", value, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgLessThan(String value) {
            addCriterion("o_img <", value, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgLessThanOrEqualTo(String value) {
            addCriterion("o_img <=", value, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgLike(String value) {
            addCriterion("o_img like", value, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgNotLike(String value) {
            addCriterion("o_img not like", value, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgIn(List<String> values) {
            addCriterion("o_img in", values, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgNotIn(List<String> values) {
            addCriterion("o_img not in", values, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgBetween(String value1, String value2) {
            addCriterion("o_img between", value1, value2, "oImg");
            return (Criteria) this;
        }

        public Criteria andOImgNotBetween(String value1, String value2) {
            addCriterion("o_img not between", value1, value2, "oImg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table offer
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 22 22:22:46 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table offer
     *
     * @mbg.generated Sat Feb 22 22:22:46 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}