package com.lxy.exchange.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_account
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_username
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    private String userUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_description
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    private String userDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_demandfinish
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    private Integer userDemandfinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_applyper
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    private Integer userApplyper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_account
     *
     * @return the value of user.user_account
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_account
     *
     * @param userAccount the value for user.user_account
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_username
     *
     * @return the value of user.user_username
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public String getUserUsername() {
        return userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_username
     *
     * @param userUsername the value for user.user_username
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_description
     *
     * @return the value of user.user_description
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public String getUserDescription() {
        return userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_description
     *
     * @param userDescription the value for user.user_description
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public void setUserDescription(String userDescription) {
        this.userDescription = userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_demandfinish
     *
     * @return the value of user.user_demandfinish
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public Integer getUserDemandfinish() {
        return userDemandfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_demandfinish
     *
     * @param userDemandfinish the value for user.user_demandfinish
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public void setUserDemandfinish(Integer userDemandfinish) {
        this.userDemandfinish = userDemandfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_applyper
     *
     * @return the value of user.user_applyper
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public Integer getUserApplyper() {
        return userApplyper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_applyper
     *
     * @param userApplyper the value for user.user_applyper
     *
     * @mbg.generated Wed Mar 04 21:01:05 CST 2020
     */
    public void setUserApplyper(Integer userApplyper) {
        this.userApplyper = userApplyper;
    }
}